source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'YTKNetwork-SWItroFiT_Example' do
  pod 'YTKNetwork-SWItroFiT', :path => '../'

  target 'YTKNetwork-SWItroFiT_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
