source 'https://cdn.cocoapods.org/'
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'YTKNetwork-SWItroFiT_Example' do
  pod 'YTKNetwork-SWItroFiT', :path => '../'

  target 'YTKNetwork-SWItroFiT_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.2'
  end
end
